---
services:
  traffik:
    image: traefik:v3.3.4
    container_name: traefik
    command: --api.insecure=true
    networks:
        - frontend
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vscode/traefik.yaml:/etc/traefik/traefik.yaml:ro
    restart: unless-stopped
networks:
  frontend:
    external: true
