---
- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Install Apache2
  apt:
    name: apache2
    state: present
  become: true

- name: Start and enable Apache2 service
  service:
    name: apache2
    state: started
    enabled: yes
  become: true
