apiVersion: networkingnetworking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-app-network-policy
spec:
  podSelector:
    matchLabels:
      app: my-app
  policyType:
    - ingress
    - egress
  ingress:
    - from:
        - podSelector: {}
        - podSelector:
            matchLabels:
              app: trusted
  egress:
    - from:
        - podSelector: {}