apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQWp0aERDak1JUVNUTi83UUdzQ1ZkalFBSzZMdnZmU21LYzVrNjRQamU2QXhUCm1MT0l1SzFNeElhUGx0WmVrMGIvKzhHU0JQMGtoL2VVQUNaUTVwRDRKRTZ1ODVNYWxtc0tNYUxsQTRRcGdNNXEKY2d6NzJOUjR0QU0yTkpGYXpkbjYrTjFWM1Fudk9KK3U3d2lQYmg4c21QdVVWOTlBVHY5K1JBRzJJMFlXckpsQQpYSlh3UGRJalJvcTBIYlZTVlhhUUJkVVpmbnRubUNPd2VlNm9CLzdwVjdic2lud1FrajU0ZXg2enAxenRxNkQ5CkJBZ3Y4QmlSdmNzNmQrNEhtMFJXVXJuVms3V1FDM2c1OFRkNHNwa2IzMlJoTjdRVW5aOTVzMlFYUnVoaThETjYKSW9kVFVZaFRaNnN4OWovWGVMODlIeXBpb212UUh0TXB4RnJPbFloOGlRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRm5wRnB1Z3NHcFlZQTYvVjNGTllDUTdpSDV0bVBaU3U3dzlOQ21vc0c3bWN1MnY4SlBSCjRaTUNWV29lbzRpWmlGdG1hZFRrN1pBSENUS0ovUU1hbDRERXFCc0EvTE42K3ZnMjFzVnBjczgvN05hTjZXdncKN3A4b09lNTQzRUs4R1lFZ1Noa1VGVkZ4UFE5Ry8zK2FUY2pKeklOMEFLWGZ6U2FKd3JUY1FVaWo5aFFWUkdncApOcURQMCtxOTBGdlVLWGh0dmZEMDZQU3BzbVgvZXpYNmc4K1RhZDJ6Rmp3d2s3MnRzRHIzL0I5Ujc1dmtLNXFkCnM2TzdJWUpyQ0pqelU2ZVpkNW81UHkzT0VORk9xS0VTNkloeUZnSUJpZXEvYmY1QzgzblhaWlEwNGNxN0hnakQKYmtaMWI2aUpGaDJjTkNSd1QyRmd4YnpHc3NGbEcyTHMxVGM9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
  signerName: kubernetes.io/kube-apiserver-client
